import React, { createContext, useCallback, useContext, useEffect, useState } from "react";

export type Language = "en" | "ur";

const translations = {
  en: {
    home: "Home",
    menu: "Menu",
    cart: "Cart",
    orders: "Orders",
    profile: "Profile",
    dealsBanner: "Today's Deals",
    dealsSubtitle: "Limited time offers",
    mostPopular: "Most Popular",
    popularSub: "Customer favourites",
    browseCategory: "Browse by Category",
    seeAll: "See All",
    dineIn: "Dine In",
    takeaway: "Takeaway",
    delivery: "Delivery",
    welcomeBack: "Welcome back!",
    orderNow: "Order Now",
    addToCart: "Add to Cart",
    proceedCheckout: "Proceed to Checkout",
    signInCheckout: "Sign In to Checkout",
    placeOrder: "Place Order",
    orderSummary: "Order Summary",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    deliveryFee: "Delivery fee",
    loyaltyPoints: "Loyalty Points",
    redeemPoints: "Redeem Points",
    pointsEarned: "Points Earned",
    yourPoints: "Your Points",
    settings: "Settings",
    language: "Language",
    notifications: "Push Notifications",
    contactUs: "Contact Us",
    terms: "Terms & Conditions",
    privacy: "Privacy Policy",
    appVersion: "App Version",
    signOut: "Sign Out",
    savedAddresses: "Delivery Addresses",
    popular: "Popular",
    spicy: "Spicy",
    isNew: "New",
    quantity: "Quantity",
    calories: "kcal per serving",
    inCart: "already in cart",
    orderType: "Order Type",
    payment: "Payment",
    note: "Note (optional)",
    specialRequests: "Special requests, allergies, extra sauce...",
    orderPlaced: "Order Placed!",
    trackOrder: "Track Order",
    backToHome: "Back to Home",
    orderReceived: "Order Received",
    preparing: "Preparing",
    ready: "Ready",
    delivered: "Delivered",
    activeOrders: "Active",
    pastOrders: "Past Orders",
    emptyCart: "Your cart is empty",
    emptyCartSub: "Add some delicious items from our menu to get started!",
    browseMenu: "Browse Menu",
    clearAll: "Clear All",
    searchMenu: "Search menu...",
    signIn: "Sign In",
    signUp: "Sign Up",
    guest: "Guest",
    continueGuest: "Continue as guest",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    continue: "Continue",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    orContinueWith: "or continue with",
    loginWithPhone: "Login with Phone",
    loginWithUsername: "Login with Username",
    homeTitle: "Authentic Taste",
    homeSubtitle: "Fresh Quality, Bold Flavours",
    viewMenu: "View Menu",
    ourStory: "Our Story",
    storyTitle: "The Hunger Bite Istanbul",
    storyDesc: "A journey of flavour from Istanbul to your table",
    ourMenu: "Our Menu",
    menuSubtitle: "Explore our handcrafted dishes",
    recommended: "You Might Also Like",
    size: "Size",
    small: "Small",
    medium: "Medium",
    large: "Large",
    checkout: "Checkout",
    deliveryAddress: "Delivery Address",
    specialInstructions: "Special Instructions",
    cashOnDelivery: "Cash on Delivery",
    cardPayment: "Card Payment",
    placeYourOrder: "Place Your Order",
    orderConfirmed: "Order Confirmed!",
    orderNumber: "Order Number",
    estimatedDelivery: "Estimated Delivery",
    minutes: "min",
    thankYou: "Thank you for your order!",
    orderHistory: "Order History",
    noOrders: "No orders yet",
    noOrdersSub: "When you place an order, it will appear here",
    viewOrder: "View Order",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    close: "Close",
    back: "Back",
    loading: "Loading...",
    error: "Something went wrong",
    retry: "Try Again",
    noResults: "No results found",
    all: "All",
    category: "Category",
    price: "Price",
    about: "About",
    contact: "Contact",
    followUs: "Follow Us",
    openingHours: "Opening Hours",
    address: "Address",
    callUs: "Call Us",
    emailUs: "Email Us",
    sendMessage: "Send Message",
    subject: "Subject",
    message: "Message",
    send: "Send",
    messageSent: "Message sent!",
    gold: "Gold",
    silver: "Silver",
    bronze: "Bronze",
    points: "points",
    tier: "Tier",
    login: "Login",
    signup: "Sign Up",
    or: "or",
    phone: "Phone",
    cardNumber: "Card Number",
    expiry: "Expiry",
    cvv: "CVV",
    cardHolder: "Cardholder Name",
    payNow: "Pay Now",
    tableReservation: "Table Reservation",
    reserveTable: "Reserve a Table",
    selectDate: "Select Date",
    selectTime: "Select Time",
    partySize: "Party Size",
    guests: "guests",
    reserveNow: "Reserve Now",
    reservationConfirmed: "Reservation Confirmed!",
    myReservations: "My Reservations",
    noReservations: "No reservations yet",
    cancelReservation: "Cancel Reservation",
    scanQR: "Scan QR Code",
    scanMenuQR: "Scan to view menu",
    available: "Available",
    outOfStock: "Out of Stock",
    lowStock: "Low Stock",
    inStock: "In Stock",
    kitchenStatus: "Kitchen Status",
    orderProgress: "Order Progress",
    preparingYourOrder: "Your order is being prepared",
    almostReady: "Almost ready!",
    outForDelivery: "Out for delivery",
    deliveredSuccess: "Delivered successfully",
  },
  ur: {
    home: "ہوم",
    menu: "مینو",
    cart: "کارٹ",
    orders: "آرڈرز",
    profile: "پروفائل",
    dealsBanner: "آج کے ڈیلز",
    dealsSubtitle: "محدود وقت کی پیشکش",
    mostPopular: "سب سے مقبول",
    popularSub: "مشتریوں کی پسندیدہ",
    browseCategory: "کیٹیگری دیکھیں",
    seeAll: "سب دیکھیں",
    dineIn: "ریستوراں میں",
    takeaway: "ٹیک اوے",
    delivery: "ڈیلیوری",
    welcomeBack: "خوش آمدید!",
    orderNow: "ابھی آرڈر کریں",
    addToCart: "کارٹ میں ڈالیں",
    proceedCheckout: "چیک آؤٹ",
    signInCheckout: "سائن ان کریں",
    placeOrder: "آرڈر دیں",
    orderSummary: "آرڈر خلاصہ",
    subtotal: "ذیلی کل",
    tax: "ٹیکس",
    total: "کل",
    deliveryFee: "ڈیلیوری فیس",
    loyaltyPoints: "لائلٹی پوائنٹس",
    redeemPoints: "پوائنٹس استعمال کریں",
    pointsEarned: "پوائنٹس ملے",
    yourPoints: "آپ کے پوائنٹس",
    settings: "ترتیبات",
    language: "زبان",
    notifications: "اطلاعات",
    contactUs: "ہم سے رابطہ",
    terms: "شرائط و ضوابط",
    privacy: "رازداری کی پالیسی",
    appVersion: "ایپ ورژن",
    signOut: "سائن آؤٹ",
    savedAddresses: "ڈیلیوری پتے",
    popular: "مقبول",
    spicy: "مسالہ دار",
    isNew: "نیا",
    quantity: "مقدار",
    calories: "کیلوری فی سرونگ",
    inCart: "کارٹ میں ہے",
    orderType: "آرڈر کی قسم",
    payment: "ادائیگی",
    note: "نوٹ (اختیاری)",
    specialRequests: "خاص گزارش، الرجی، اضافی چٹنی...",
    orderPlaced: "آرڈر ہو گیا!",
    trackOrder: "آرڈر ٹریک کریں",
    backToHome: "ہوم پر واپس",
    orderReceived: "آرڈر موصول",
    preparing: "تیاری جاری",
    ready: "تیار ہے",
    delivered: "پہنچ گیا",
    activeOrders: "فعال",
    pastOrders: "پرانے آرڈر",
    emptyCart: "کارٹ خالی ہے",
    emptyCartSub: "مینو سے کچھ لذیذ چیزیں شامل کریں!",
    browseMenu: "مینو دیکھیں",
    clearAll: "سب ہٹائیں",
    searchMenu: "مینو تلاش کریں...",
    signIn: "سائن ان",
    signUp: "سائن اپ",
    guest: "مہمان",
    continueGuest: "مہمان کے طور پر جاری رکھیں",
    fullName: "پورا نام",
    phoneNumber: "فون نمبر",
    continue: "جاری رکھیں",
    email: "ای میل",
    password: "پاس ورڈ",
    confirmPassword: "پاس ورڈ کی تصدیق",
    orContinueWith: "یا جاری رکھیں",
    loginWithPhone: "فون سے لاگ ان",
    loginWithUsername: "صارف نام سے لاگ ان",
    homeTitle: "اصل ذائقہ",
    homeSubtitle: "تازہ معیار، بولڈ ذائقے",
    viewMenu: "مینو دیکھیں",
    ourStory: "ہماری کہانی",
    storyTitle: "دہنگر بائٹ استنبول",
    storyDesc: "استنبول سے آپ کی میز تک ذائقے کا سفر",
    ourMenu: "ہمارا مینو",
    menuSubtitle: "ہمارے ہاتھ سے بنے ڈشز دریافت کریں",
    recommended: "آپ کو یہ بھی پسند آ سکتا ہے",
    size: "سائز",
    small: "چھوٹا",
    medium: "درمیانی",
    large: "بڑا",
    checkout: "چیک آؤٹ",
    deliveryAddress: "ڈیلیوری پتہ",
    specialInstructions: "خصوصی ہدایات",
    cashOnDelivery: "ڈیلیوری پر نقد",
    cardPayment: "کارڈ ادائیگی",
    placeYourOrder: "اپنا آرڈر دیں",
    orderConfirmed: "آرڈر کی تصدیق!",
    orderNumber: "آرڈر نمبر",
    estimatedDelivery: "estimated ڈیلیوری",
    minutes: "منٹ",
    thankYou: "آپ کے آرڈر کا شکریہ!",
    orderHistory: "آرڈر کی تاریخ",
    noOrders: "ابھی تک کوئی آرڈر نہیں",
    noOrdersSub: "جب آپ آرڈر دیں گے، وہ یہاں نظر آئے گا",
    viewOrder: "آرڈر دیکھیں",
    cancel: "منسوخ",
    save: "محفوظ",
    edit: "ترمیم",
    delete: "حذف",
    close: "بند",
    back: "واپس",
    loading: "لوڈ ہو رہا ہے...",
    error: "کچھ غلط ہو گیا",
    retry: "دوبارہ کوشش کریں",
    noResults: "کوئی نتائج نہیں ملے",
    all: "سب",
    category: "کیٹیگری",
    price: "قیمت",
    about: "کے بارے میں",
    contact: "رابطہ",
    followUs: "ہمیں فالو کریں",
    openingHours: "کھلنے کے اوقات",
    address: "پتہ",
    callUs: "ہمیں کال کریں",
    emailUs: "ای میل کریں",
    sendMessage: "پیجھ بھیجیں",
    subject: "موضوع",
    message: "پیغام",
    send: "بھیجیں",
    messageSent: "پیغام بھیج دیا گیا!",
    gold: "سنہرا",
    silver: "چاندی",
    bronze: "کانسی",
    points: "پوائنٹس",
    tier: "等级",
    login: "لاگ ان",
    signup: "سائن اپ",
    or: "یا",
    phone: "فون",
    cardNumber: "کارڈ نمبر",
    expiry: "میعاد",
    cvv: "CVV",
    cardHolder: "کارڈ ہولڈر کا نام",
    payNow: "ابھی ادائیگی کریں",
    tableReservation: "ٹیبل ریزرویشن",
    reserveTable: "ٹیبل محفوظ کریں",
    selectDate: "تاریخ منتخب کریں",
    selectTime: "وقت منتخب کریں",
    partySize: "پارٹی کا سائز",
    guests: "مہمان",
    reserveNow: "ابھی محفوظ کریں",
    reservationConfirmed: "ریزرویشن کی تصدیق!",
    myReservations: "میری ریزرویشن",
    noReservations: "ابھی تک کوئی ریزرویشن نہیں",
    cancelReservation: "ریزرویشن منسوخ",
    scanQR: "QR کوڈ اسکین کریں",
    scanMenuQR: "مینو دیکھنے کے لیے اسکین کریں",
    available: "دستیاب",
    outOfStock: "ختم ہو گیا",
    lowStock: "کم اسٹاک",
    inStock: "اسٹاک میں",
    kitchenStatus: "کچن کی صورتحال",
    orderProgress: "آرڈر کی پیشرفت",
    preparingYourOrder: "آپ کا آرڈر تیار ہو رہا ہے",
    almostReady: "تقریباً تیار!",
    outForDelivery: "ڈیلیوری کے لیے نکلا",
    deliveredSuccess: "کامیابی سے پہنچا دیا",
  },
};

export type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKeys) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("thb_language");
    if (saved === "en" || saved === "ur") {
      setLanguageState(saved);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dir = language === "ur" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("thb_language", lang);
  }, []);

  const t = useCallback(
    (key: TranslationKeys): string => {
      return (translations[language] as Record<string, string>)[key] ?? (translations.en as Record<string, string>)[key] ?? key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL: language === "ur" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
